apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
  name: prometheus
  namespace: tanzu-system-monitoring
spec:
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      loadBalancerPolicy:
        strategy: Cookie
      services:
        - name: prometheus-server
          port: 80
  virtualhost:
    fqdn: prometheus.nirs.lab
#    tls:
#      secretName: cnd-tls/wild-tls
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
  name: grafana
  namespace: tanzu-system-monitoring
spec:
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      loadBalancerPolicy:
        strategy: Cookie
      services:
        - name: grafana
          port: 80
  virtualhost:
    fqdn: grafana.nirs.lab
#    tls:
#      secretName: cnd-tls/wild-tls
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
  name: alertmanager
  namespace: tanzu-system-monitoring
spec:
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      loadBalancerPolicy:
        strategy: Cookie
      services:
        - name: prometheus-alertmanager
          port: 80
  virtualhost:
    fqdn: alertmanager.nirs.lab
#    tls:
#      secretName: cnd-tls/wild-tls

