apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-deployment
  labels:
    app: wildfly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wildfly
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      containers:
      - name: wildfly
        image: ext-harbor.cnd.lab/jboss/wildfly:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
#      nodeSelector:
#        key: worker
