apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: workload01
  namespace: cnd-infra
spec:
  distribution:
    version: 1.20.9
  topology:
    controlPlane:
      count: 1
      class: best-effort-small
      storageClass: tanzu-storage-policy
      # volumes: 
      #   - name: etcd
      #     mountPath: /var/lib/etcd
      #     capacity:
      #       storage: 4Gi
    workers:
      count: 3
      class: best-effort-large
      storageClass: tanzu-storage-policy
      volumes: 
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 16Gi
  settings:
    storage:
      defaultClass: tanzu-storage-policy
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["20.20.16.0/21"]
      pods:
        cidrBlocks: ["20.20.0.0/21"]
