apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: cnd-cluster-network
  namespace: cnd-infra
spec:
  distribution:
    version: 1.19.7+vmware.1-tkg.1.fc82c41
  topology:
    controlPlane:
      count: 3
      class: best-effort-small
      storageClass: tanzu-storage-policy
      # volumes: 
      #   - name: etcd
      #     mountPath: /var/lib/etcd
      #     capacity:
      #       storage: 4Gi
    workers:
      count: 3
      class: best-effort-large
      storageClass: tanzu-storage-policy
      volumes: 
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 32Gi
#  settings:
#    storage:
#      defaultClass: tanzu-storage-policy
#    network:
#      cni:
#        name: antrea
#      services:
#        cidrBlocks: ["10.96.0.0/22"]
#      pods:
#        cidrBlocks: ["10.244.0.0/19"]
