apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotation:
    projectcontour.io/tls-minimum-protocol-version: "TLSv1_3"
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: "/"
    kubernetes.io/ingress.class: "contour"
  name: jenkins
  namespace: jenkins
spec:
  virtualhost:
    fqdn: jenkins.cnd.lab
    tls:
      secretName: cnd-tls/wild-tls
  routes:
  - services:
    - name: jenkins
      port: 8080
    conditions:
    - prefix: /
