apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-apiserver
  namespace: tanzu-system-monitoring
  labels:
    app: custom-metrics-apiserver
spec:
  ports:
  - port: 443
    targetPort: 6443
  selector:
    app: custom-metrics-apiserver
